language: android

env:
    global:
      - ADB_INSTALL_TIMEOUT=8

android:
  components:
  - tools
  - platform-tools
  - build-tools-23.0.2
  - android-23
  - extra-android-m2repository
  - extra-google-m2repository
  - extra-google-google_play_services

    licenses:
      - 'android-sdk-license-.+'

before_script:
  - echo no | android create avd --force --name test --target android-23 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window -gpu off -no-boot-anim &
  - android-wait-for-emulator
  - adb devices
  - adb shell input keyevent 82 &

script:
  - echo $ADB_INSTALL_TIMEOUT
  - android list target
  - ./gradlew connectedAndroidTest
